### ISSUE TITLE
Verifying the hostkey_hash?

### ISSUE THREAD

**Issue by adamjaso** [ParallelSSH/ssh2-python#10]
I've been looking through the code for a way to verify the libssh2_hostkey_hash, but so far, cannot see a way to do this. Am I missing something?

**Comment by pkittenis** [comment]
Hi there, thanks for the interest.

No, you are not missing anything. The host key related methods is the only part of the libssh2 API that is not yet implemented in ssh2-python ( blocked by #2 ).

The `hostkey_hash` method returning a hash of the server key will be in the next release, the rest not until subsequent releases.

**Comment by pkittenis** [comment]
Closing - please watch #2 for status of `host_*` functions implementation.
