### ISSUE TITLE
session.handshake(socket) hanging for at least 5 minutes

### ISSUE THREAD

**Issue by hakaishi** [ParallelSSH/ssh2-python#109]
An error is raised immediately when the port is not available, but if I use a port that is not used for ssh it will hang for 5 minutes.
My system runs vsftp, so port 21 is open.
I tried the following:
```
sock = socket(AF_INET, SOCK_STREAM)
sock.settimeout(3)
sock.connect(("localhost", 21))
sock.settimeout(3)
cli = Session()
cli.handshake(sock)

cli.userauth_password("name", "password")
```
Result:
The code will hang for 5 minutes at `cli.handshake(sock)`
I would expect to be able to set an reasonable timeout until an error is raised. For example 10 seconds.
I can't let the user to wait 5 minutes until he gets the feedback that the port is wrong.

**Comment by pkittenis** [comment]
Libssh2 has it's own timeout that needs setting.

See [Session.set_timeout](https://ssh2-python.readthedocs.io/en/latest/session.html#ssh2.session.Session.set_timeout)

**Comment by hakaishi** [comment]
Omg! So there was one and I overlooked it. Sorry 😥
