### ISSUE TITLE
Raspberrypi docker image error

### ISSUE THREAD

**Issue by invictusro** [ParallelSSH/ssh2-python#120]
Hello guys so I do want to build a docker container. I do have a Raspberrypi with a flask app and I'm using multiple libraries. 
Every library is installed succesfully until I hit this:

>  Running setup.py install for ssh2-python: started
>  Running setup.py install for ssh2-python: finished with status 'error'

This seems to be the cause of the error:

> /bin/sh: 1: cmake: not found

I have tried to follow some questions from stack but none of them worked. Does any of you know what can be the cause ?
Here are the packages installed by me:

> mysql-connector==2.2.9
> Flask==1.0.2
> getmac==0.8.2
> ssh2-python==0.19.0

**Comment by aveach** [comment]
Install cmake in your docker image before attempting to install this package? 

`sudo apt-get install cmake`
