### ISSUE TITLE
runtime_library_dirs causes fail on windows

### ISSUE THREAD

**Issue by judd-taylor** [ParallelSSH/ssh2-python#122]
After installing openssl/zlib, run 'pip install ssh2-python'

The stack trace from pip looks like this:

  copying ssh2\listener.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\listener.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\pkey.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\pkey.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\pkey.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\publickey.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\publickey.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\publickey.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\session.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\session.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\session.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\sftp.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\sftp.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\sftp.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\sftp_handle.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\sftp_handle.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\sftp_handle.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\statinfo.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\statinfo.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\statinfo.pyx -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\utils.c -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\utils.pxd -> build\lib.win-amd64-3.9\ssh2
  copying ssh2\utils.pyx -> build\lib.win-amd64-3.9\ssh2
  running build_ext
  building 'ssh2.agent' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\ssh2
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ilibssh2/include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.240.0_x64__qbz5n2kfra8p0\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcssh2\agent.c /Fobuild\temp.win-amd64-3.9\Release\ssh2\agent.obj
  agent.c
  warning: I don't know what to do with 'runtime_library_dirs': ['$ORIGIN/.']
  error: don't know how to set runtime library search path for MSVC
  ----------------------------------------
  ERROR: Failed building wheel for ssh2-python

I'm also not able to build using the system libssh2 (it doesn't prompt for a path, but I installed in /usr/local to make it happy). That fails linking saying it can't find libcryptoAD64.lib, which I find no reference to anywhere. I tried building from the source as well, editing setup.py to set runtime_library_dirs = [] and that fails for some other reason.

**Comment by pkittenis** [comment]
From source builds on Windows are a PITA - good luck. Best to use the pre-made wheels up to python 3.8. 3.9 is still not officially released.

Can try to follow from [source instructions here](https://ssh2-python.readthedocs.io/en/latest/installation.html#system-library-build) after installing libssh2 - see windows [CI configuration](https://github.com/ParallelSSH/ssh2-python/blob/master/.appveyor.yml)

General Windows question, not an issue with library - out of scope for issue tracker.

**Comment by judd-taylor** [comment]
I was thinking 3.9 should have worked. I dropped back to 3.8 and everything went perfectly. Thanks!
