### ISSUE TITLE
How to change cipher preference?

### ISSUE THREAD

**Issue by dyakhnov** [ParallelSSH/ssh2-python#125]
Can't find this in examples as well as in the code, so here is the question:
> Is there any way to change default chiper (aes-128-ctr) to something else?

**Comment by pkittenis** [comment]
Please use the [mail group](https://groups.google.com/forum/#!forum/ssh2-python) for questions and discussion - the issue tracker is for reporting issues with the library.

This is probably a better question for the [libssh2 mail list](https://libssh2.org/mail.cgi) - not aware of any way in the API to choose cipher.
