### ISSUE TITLE
Documentation suggesting incorrect flags for sftp.open()

### ISSUE THREAD

**Issue by gvialetto** [ParallelSSH/ssh2-python#13]
__Steps to reproduce:__

Simply use the code in the README file to read a file from SFTP:

```python
sftp = session.sftp_init()
with sftp.open(<remote file to read>, 0, 0) as remote_fh, \
        open(<file to write>, 'wb') as local_fh:
    for size, data in remote_fh:
        local_fh.write(data)
```

__Expected behaviour:__

Data is copied from the remote file to the local file.

__Actual behaviour:__

No data is ever written to `<file to write>`. The size parameter is set by libssh2 to ``LIBSSH2_ERROR_SFTP_PROTOCOL`` (-31) and the calling `sftp.last_error()` will report ``LIBSSH2_FX_FAILURE`` (4). ``remote_fh.fstat()`` will succeed without issues (reporting correct data).

__Additional info:__

Version ``ssh2-python 0.6.0`` with bundled ``libssh2``.

This seems to happen because (at least up to ``libssh2`` 1.8.0) ``0`` and ``LIBSSH2_FXF_READ`` are not synonyms, like it is (in my understanding) incorrectly suggested in the [documentation](https://github.com/ParallelSSH/ssh2-python/blob/master/ssh2/sftp.pyx#L157) and the examples ([sftp_read.py](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/sftp_read.py#L40), for example). This may be tested using ``libssh2`` directly by changing line 251 of the [``sftp.c``](https://github.com/libssh2/libssh2/blob/master/example/sftp.c) example from:
```c
libssh2_sftp_open(sftp_session, sftppath, LIBSSH2_FXF_READ, 0);
```
to
```c
libssh2_sftp_open(sftp_session, sftppath, 0, 0);
```
This will make ``libssh2_sftp_read()`` fail in in the same way described in the actual behaviour.

I should be able to send a pull request to fix the documentation and examples if needed (and my understanding of the issue is correct).

**Comment by pkittenis** [comment]
Hi there,

Thank you for the interest and the report!

At the moment I am not able to replicate this. Can you please show complete example code that replicates the issue?

Tested with the example [sftp_read.py](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/sftp_read.py#L40) with no changes and size was non-negative. Also modified it to write to a local file like in the readme, as per below:

```
    with sftp.open(args.file, 0, 0) as fh, \
         open('test.copy', 'wb') as local_fh:
        for size, data in fh:
            local_fh.write(data)
```

No errors. Copied file is identical.

```
$ diff test.copy ~/test
$ echo $?
0
```

Same code is also [integration tested here](https://github.com/ParallelSSH/ssh2-python/blob/master/tests/test_sftp.py#L32) with `0` used as argument.

All tests with libssh2 `1.8.0-1`.

**Comment by pkittenis** [comment]
Hi there,

Thanks for checking and the great investigation! That all sounds reasonable, I have only ever integration tested with OpenSSH (or compatible) servers so is quite likely that other servers do not follow the `0 == read` convention.

So documentation, API and readthedocs both, as well as example code need updating to use the `LIBSSH2_FXF_READ`. 

If you'd like to take that on I would be very happy to accept a PR for it. Thanks again for the report.
