### ISSUE TITLE
mistake in documentation? - fstat does not return a tuple

### ISSUE THREAD

**Issue by hakaishi** [ParallelSSH/ssh2-python#132]
Link to documentation: https://ssh2-python.readthedocs.io/en/latest/sftp_handle.html#ssh2.sftp_handle.SFTPHandle.fsetstat
Problem: SFTPHandle.fsetstat only returns ssh2.sftp_handle.SFTPAttributes and not a tuple (int, SFTPAttributes) like it is currently written.

Is this just a documentation issue or a wrong implementation?

**Comment by pkittenis** [comment]
Documentation needs updating.
