### ISSUE TITLE
Wrong documentation? - SFTPHandle.read returns tuple

### ISSUE THREAD

**Issue by hakaishi** [ParallelSSH/ssh2-python#133]
documentation url: https://ssh2-python.readthedocs.io/en/latest/sftp_handle.html#ssh2.sftp_handle.SFTPHandle.read

Problem: Documentation says that read returns bytes, but it actually returns a tuple of (return code, bytes)

**Comment by pkittenis** [comment]
Thanks for the interest.

Yes, documentation is wrong, it should be a tuple. PR to update them is welcome.
