### ISSUE TITLE
[Feature request] manylinux2014 wheels

### ISSUE THREAD

**Issue by hujkis** [ParallelSSH/ssh2-python#144]
As stated in [PEP 599](https://www.python.org/dev/peps/pep-0599/) Rationale: "CentOS 6 is now the oldest supported CentOS release, and will receive maintenance updates through November 30th, 2020, at which point it will reach end-of-life, and no further updates such as security patches will be made available. All wheels built under the manylinux2010 images will remain at obsolete versions after that point."

Would it be possible to start building wheels using manylinux2014? This would also enable creating wheels on architectures supported by CentOS7 (x86_64, i686, aarch64, armv7l, ppc64, ppc64le, s390x)

I don't fully understand the CI pipeline here, but have tried to rebuild wheels manually on s390x, ppc64le, aarch64 CentOS7 and can confirm there are no extra steps needed, compared to x86_64.

Please let me know if I can somehow help.

**Comment by pkittenis** [comment]
Thanks for the interest and report.

PR welcome. Can refer to the [existing manylinux2010 script](https://github.com/ParallelSSH/ssh2-python/blob/master/ci/travis/build-manylinux.sh) and [dockerfile](https://github.com/ParallelSSH/ssh2-python/tree/master/ci/docker/manylinux).

There is not enough use to justify adding building wheels for other architectures as part of a release.

**Comment by pkittenis** [comment]
Provided in `0.27.0`, as well as ARM wheels.
