### ISSUE TITLE
Source code files included in installed distribution

### ISSUE THREAD

**Issue by malthe** [ParallelSSH/ssh2-python#147]
__Steps to reproduce:__

1. Install using "pip" from source distribution.

__Expected behaviour:__ [What was expected to happen.]

Only Python module files and binary code is installed in site-packages.

__Actual behaviour:__ [What actually happened.]

Source code (e.g. "session.c") is included.

__Additional info:__ [Include version of ``libssh2`` and any other relevant information.]

<img width="531" alt="image" src="https://user-images.githubusercontent.com/26405/122115654-3cd21200-ce14-11eb-91bb-aab9337a4390.png">

**Comment by pkittenis** [comment]
Source distribution will include source files.
