### ISSUE TITLE
fatal error occurs

### ISSUE THREAD

**Issue by dengjiuhong** [ParallelSSH/ssh2-python#15]
### Bug reports

__Actual behaviour:
the following error occurs some times.

__Additional info:

libssh2 - libssh2 1.8.0
ssh2-python 0.6.0

*** glibc detected *** python: double free or corruption (fasttop): 0x000000000110c170 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3080a75e66]
/usr/lib64/libcrypto.so.10(CRYPTO_free+0x1d)[0x3d0c06ad5d]
/usr/lib64/libcrypto.so.10(OBJ_NAME_add+0x92)[0x3d0c06ddc2]
/usr/lib64/libcrypto.so.10(EVP_add_cipher+0x27)[0x3d0c0f0fe7]
/usr/lib64/libcrypto.so.10(OpenSSL_add_all_ciphers+0x3eb)[0x3d0c0f559b]
/usr/lib64/libcrypto.so.10(OPENSSL_add_all_algorithms_noconf+0xe)[0x3d0c0f519e]
/usr/lib64/libssh2.so.1(libssh2_init+0x39)[0x361221e5b9]
/usr/lib64/libssh2.so.1(libssh2_session_init_ex+0xae)[0x3612212e4e]
/home/jobcenter/python-env/lib/python2.7/site-packages/ssh2/session.so(+0x65b7)[0x7faf5440f5b7]
python[0x46ded3]
python(PyObject_Call+0x47)[0x419ba7]
python(PyEval_EvalFrameEx+0x6a0b)[0x4aa8bb]
python(PyEval_EvalCodeEx+0x877)[0x4ad257]
python[0x5114a8]
python(PyObject_Call+0x47)[0x419ba7]
python(PyEval_EvalFrameEx+0x5c91)[0x4a9b41]
python(PyEval_EvalFrameEx+0x7e42)[0x4abcf2]
python(PyEval_EvalCodeEx+0x877)[0x4ad257]
python[0x5114a8]
python(PyObject_Call+0x47)[0x419ba7]
python(PyEval_EvalFrameEx+0x5c91)[0x4a9b41]
python(PyEval_EvalFrameEx+0x7e42)[0x4abcf2]
python(PyEval_EvalFrameEx+0x7e42)[0x4abcf2]
python(PyEval_EvalCodeEx+0x877)[0x4ad257]
python[0x5113ae]
python(PyObject_Call+0x47)[0x419ba7]
python[0x42296f]
python(PyObject_Call+0x47)[0x419ba7]
python(PyEval_CallObjectWithKeywords+0x43)[0x4a2d83]
python[0x4e59e2]
/lib64/libpthread.so.0[0x34802079d1]
/lib64/libc.so.6(clone+0x6d)[0x3080ae89dd]
======= Memory map: ========
00400000-0057b000 r-xp 00000000 08:02 917739                             /home/jobcenter/python-env/bin/python
0077b000-007b7000 rw-p 0017b000 08:02 917739                             /home/jobcenter/python-env/bin/python
007b7000-007c6000 rw-p 00000000 00:00 0
01034000-018e3000 rw-p 00000000 00:00 0                                  [heap]
3080200000-3080220000 r-xp 00000000 08:02 262555                         /lib64/ld-2.12.so
308041f000-3080420000 r--p 0001f000 08:02 262555                         /lib64/ld-2.12.so
3080420000-3080421000 rw-p 00020000 08:02 262555                         /lib64/ld-2.12.so
3080421000-3080422000 rw-p 00000000 00:00 0
3080600000-3080602000 r-xp 00000000 08:02 262558                         /lib64/libdl-2.12.so
3080602000-3080802000 ---p 00002000 08:02 262558                         /lib64/libdl-2.12.so
3080802000-3080803000 r--p 00002000 08:02 262558                         /lib64/libdl-2.12.so
3080803000-3080804000 rw-p 00003000 08:02 262558                         /lib64/libdl-2.12.so
3080a00000-3080b8a000 r-xp 00000000 08:02 262556                         /lib64/libc-2.12.so
3080b8a000-3080d8a000 ---p 0018a000 08:02 262556                         /lib64/libc-2.12.so
3080d8a000-3080d8e000 r--p 0018a000 08:02 262556                         /lib64/libc-2.12.so
3080d8e000-3080d8f000 rw-p 0018e000 08:02 262556                         /lib64/libc-2.12.so
3080d8f000-3080d94000 rw-p 00000000 00:00 0
3081600000-3081615000 r-xp 00000000 08:02 262568                         /lib64/libz.so.1.2.3
3081615000-3081814000 ---p 00015000 08:02 262568                         /lib64/libz.so.1.2.3
3081814000-3081815000 r--p 00014000 08:02 262568                         /lib64/libz.so.1.2.3
3081815000-3081816000 rw-p 00015000 08:02 262568                         /lib64/libz.so.1.2.3
3081a00000-3081a83000 r-xp 00000000 08:02 262569                         /lib64/libm-2.12.so
3081a83000-3081c82000 ---p 00083000 08:02 262569                         /lib64/libm-2.12.so
3081c82000-3081c83000 r--p 00082000 08:02 262569                         /lib64/libm-2.12.so
3081c83000-3081c84000 rw-p 00083000 08:02 262569                         /lib64/libm-2.12.so
3082600000-3082604000 r-xp 00000000 08:02 262571                         /lib64/libuuid.so.1.3.0
3082604000-3082803000 ---p 00004000 08:02 262571                         /lib64/libuuid.so.1.3.0
3082803000-3082804000 rw-p 00003000 08:02 262571                         /lib64/libuuid.so.1.3.0
3082a00000-3082a16000 r-xp 00000000 08:02 262580                         /lib64/libresolv-2.12.so
3082a16000-3082c16000 ---p 00016000 08:02 262580                         /lib64/libresolv-2.12.so
3082c16000-3082c17000 r--p 00016000 08:02 262580                         /lib64/libresolv-2.12.so
3082c17000-3082c18000 rw-p 00017000 08:02 262580                         /lib64/libresolv-2.12.so
3082c18000-3082c1a000 rw-p 00000000 00:00 0
3082e00000-3082e02000 r-xp 00000000 08:02 262234                         /lib64/libutil-2.12.so
3082e02000-3083001000 ---p 00002000 08:02 262234                         /lib64/libutil-2.12.so
3083001000-3083002000 r--p 00001000 08:02 262234                         /lib64/libutil-2.12.so
3083002000-3083003000 rw-p 00002000 08:02 262234                         /lib64/libutil-2.12.so
3086e00000-3086e02000 r-xp 00000000 08:02 262506                         /lib64/libkeyutils.so.1.3
3086e02000-3087001000 ---p 00002000 08:02 262506                         /lib64/libkeyutils.so.1.3
3087001000-3087002000 r--p 00001000 08:02 262506                         /lib64/libkeyutils.so.1.3
3087002000-3087003000 rw-p 00002000 08:02 262506                         /lib64/libkeyutils.so.1.3
3480200000-3480217000 r-xp 00000000 08:02 262195                         /lib64/libpthread-2.12.so
3480217000-3480417000 ---p 00017000 08:02 262195                         /lib64/libpthread-2.12.so
3480417000-3480418000 r--p 00017000 08:02 262195                         /lib64/libpthread-2.12.so
3480418000-3480419000 rw-p 00018000 08:02 262195                         /lib64/libpthread-2.12.so
3480419000-348041d000 rw-p 00000000 00:00 0
360f200000-360f203000 r-xp 00000000 08:02 262369                         /lib64/libcom_err.so.2.1
360f203000-360f402000 ---p 00003000 08:02 262369                         /lib64/libcom_err.so.2.1
360f402000-360f403000 r--p 00002000 08:02 262369                         /lib64/libcom_err.so.2.1
360f403000-360f404000 rw-p 00003000 08:02 262369                         /lib64/libcom_err.so.2.1
3611200000-36112db000 r-xp 00000000 08:02 262371                         /lib64/libkrb5.so.3.3
36112db000-36114db000 ---p 000db000 08:02 262371                         /lib64/libkrb5.so.3.3
36114db000-36114e5000 r--p 000db000 08:02 262371                         /lib64/libkrb5.so.3.3
36114e5000-36114e7000 rw-p 000e5000 08:02 262371                         /lib64/libkrb5.so.3.3
3611600000-3611641000 r-xp 00000000 08:02 262380                         /lib64/libgssapi_krb5.so.2.2Aborted

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report. Can you please show code that reproduces this? If not 100% reproducible, under what conditions does it happen?

**Comment by pkittenis** [comment]
Please re-open with code that produces error - step (1) in issue template.
