### ISSUE TITLE
Macos ARM architecture wheel

### ISSUE THREAD

**Issue by gersmann** [ParallelSSH/ssh2-python#159]
I noticed, that there doesn't seem to be a binary wheel for Macos M1 (ARM arch). I did run ci/osx-wheel.sh locally and build a wheel distribution. Could I somehow make that available to you, so that it can be included in the package?

**Comment by pkittenis** [comment]
Thanks for the interest.

Unless an ARM OSX target appears on CircleCI there isn't going to be an arm wheel published. While it's nice you can make one, it needs to be automated as part of the release to be of use, which means support on CircleCI.

Unlikely unless that architecture gets a lot more products.

**Comment by gersmann** [comment]
Ah, yes. But would it be possible to create a universal binary, like that:

`CMAKE_OSX_ARCHITECTURES=arm64;x86_64`

**Comment by pkittenis** [comment]
That's for cross-compiling and would only work for cmake. The python wheel build does not use cmake, that's only for libssh2 itself.

**Comment by gersmann** [comment]
Ah ok, thx.

**Comment by gersmann** [comment]
@pkittenis thanks for the excellent lib, by the way, it's been a very nice upgrade from the previous library we've been using.

**Comment by pkittenis** [comment]
Have a look at the high level clients in [parallel-ssh](https://github.com/ParallelSSH/parallel-ssh) if you haven't already. This library is intentionally not high level.

**Comment by tanzim** [comment]
Now that CircleCI supports Apple Silicone, time for a revisit?
https://support.circleci.com/hc/en-us/articles/360056461452-Apple-M1-Apple-Silion-Support-on-CircleCI
