### ISSUE TITLE
Remove Python 2 support badge

### ISSUE THREAD

**Issue by jakeanq** [ParallelSSH/ssh2-python#177]
For various reasons I happened to be trying to install the latest version of ssh2-python on Python 2 and it no longer works (due to Python3-only syntax in setup.py) - this is nothing surprising, but the badges on the README page and pypi still indicates that the project has Python 2 support.

It would be good to remove this indication.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report.

Badges and supported Python version qualifiers have been updated by 1.0.0 release.
