### ISSUE TITLE
Fail to open a shell

### ISSUE THREAD

**Issue by xavierhardy** [ParallelSSH/ssh2-python#18]
### Bug report

Using `libssh2` examples, I tried opening shell inside a channel in `ssh2-python` and it failed. I need to have a channel and a shell kept open for re-use. I cannot use `exec` because using `exec` to run a command closes the channel (which is expected).

Here is an example in the tests of `libssh2`:
https://github.com/libssh2/libssh2/blob/master/tests/ssh2.c#L152
`libssh2_channel_shell` is a macro:
https://github.com/libssh2/libssh2/blob/master/include/libssh2.h#L775

I get a `LIBSSH2_ERROR_SOCKET_DISCONNECT` error code (`-13`) when trying to open the shell.
https://github.com/libssh2/libssh2/blob/master/include/libssh2.h#L451

__Steps to reproduce:__

Run the SSH daemon locally and add an SSH public key to the `authorized_hosts` file of any user (here `root`)

Run the following Python script.

```py
#!/usr/bin/env python
import socket

from ssh2.session import Session
from ssh2.utils import version

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(("localhost", 22))
session = Session()
session.handshake(sock)
session.userauth_publickey_fromfile(
    "root", "/root/.ssh/id_rsa.pub", "/root/.ssh/id_rsa", ""
)
channel = session.open_session()
print("pty")
err_code = channel.pty()
print(err_code)
print("shell")
err_code = channel.process_startup("shell", "")
print(err_code)

channel.close()
```
```
pty
0
shell
-13
```
__Expected behaviour:__ 0 error code on shell request

__Actual behaviour:__ error on shell request

__Additional info:__ 
libssh2-1:amd64            1.5.0-2ubuntu0.1
libssh2-1-dev:amd64        1.5.0-2ubuntu0.1
python-libssh2             1.0.0-1.2

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report.

Yes, this is an issue with the `process_startup` function. For shell requests, no message should be sent but the function does not allow that. An empty string as the message (as opposed to no message), is not accepted by the server which terminates the connection.

The next version will have a `channel.shell()` function which was missing - the libssh2 macro for shell process startup - as well as a revised `process_startup` which allows for empty messages.

From next version onwards:

```
channel = session.open_session()
channel.shell()
channel.write('my command\n')
size, data = channel.read()
<..>
```

Note that a pty is not explicitly required for interactive shells though it may be used.

**Comment by xavierhardy** [comment]
Yes indeed, the macro in libssh2 uses a null pointer as message. My knowledge of Cython is limited, but I'll try to submit a pull request if I find the time. Thanks a lot!

**Comment by xavierhardy** [comment]
That was fast, it's small fix but still. Thanks a lot, though I will open a new ticket. I would like to test your branch and the only way to find how to build it was to look at Travis. Keep up the good work!
