### ISSUE TITLE
SFTP False error raised during open

### ISSUE THREAD

**Issue by maxux** [ParallelSSH/ssh2-python#23]
Using git version (master) of the `ssh2-python`, the sftp open code doesn't handle the `LIBSSH2_ERROR_EAGAIN` and raise it as an error (since c2e5381bb4dffa1632219310277e96529f88a516)

I made a small patch which fix the issue on my local setup, which was raising all the time an error when trying to use sftp, because of the `LIBSSH2_ERROR_EAGAIN`, but this is probably but the most efficient way you want to commit (this is why I didn't made any Pull Request).

The patch: https://github.com/maxux/ssh2-python/commit/7dc38339f70bf7af848ee5e6f33345feb20043dd

Based on the C exemple here: http://yoyakuweb.com/lib/libssh2-1.4.3/libssh2-1.4.3/example/sftp_nonblock.c
Some `waitsocket` workaround should be done and not a loop like me.

Anyway, the `LIBSSH2_ERROR_EAGAIN` should definitively be handled during sftp open call.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report - yes, it should be checking for EAGAIN. That is in a dev branch and due for next release.

**Comment by maxux** [comment]
Is this already pushed ?

**Comment by pkittenis** [comment]
Not merged to master yet. In progress development is at [exceptions branch](https://github.com/ParallelSSH/ssh2-python/tree/exceptions).
