### ISSUE TITLE
No source/linux ssh2-python 0.11 available on pypi

### ISSUE THREAD

**Issue by maxux** [ParallelSSH/ssh2-python#24]
From here https://pypi.python.org/simple/ssh2-python/ it looks like the `0.11` version of `ssh2-python` doesn't exists as source (.tar.gz) nor linux wheel. Something went wrong with the build ?

By the way, openssl `1.0.2n` is not available anymore since today, need to upgrade to openssl `1.0.2o`

This issue with pypi make all linux client stuck on `ssh2-python 0.10` and can't upgrade.

**Comment by pkittenis** [comment]
Thanks for raising!

The release build failed on Travis-CI and hence nothing was released to PyPi. Windows wheels are from appveyor which completed successfully. Have made a new release to fix the CI issues.
