### ISSUE TITLE
Does ssh2-python support Dynamic Port Forwarding?

### ISSUE THREAD

**Issue by pttdev** [ParallelSSH/ssh2-python#27]
I manage to create an socks5 using dynamic port forwarding with assynssh library. I tried to use ssh2-python instead but don't know where to begin. It be great if anyone can show me the way. Thank you very much!

**Comment by pkittenis** [comment]
Yes, with the `direct_tcpip_ex` function.

See [docs](http://ssh2-python.readthedocs.io/en/latest/session.html#ssh2.session.Session.direct_tcpip_ex) and libssh2 [examples](https://www.libssh2.org/examples/direct_tcpip.html).
