### ISSUE TITLE
add possibility to use system-wide libssh2

### ISSUE THREAD

**Issue by ignatenkobrain** [ParallelSSH/ssh2-python#30]
I'm packaging ssh2-python for Fedora and we have policy to not bundle things. It would be very nice if you would provide option to use system libssh2.

**Comment by ignatenkobrain** [comment]
My bad, I didn't see that it already does this.

**Comment by pkittenis** [comment]
Also have a look at the [docker files in the repository](https://github.com/ParallelSSH/ssh2-python/tree/master/ci/docker) for some distributions, including Fedora, that can be used as basis. See also [documentation](https://ssh2-python.readthedocs.io/en/latest/installation.html#system-binary-packages) and [build script](https://github.com/ParallelSSH/ssh2-python/blob/master/ci/docker/build-packages.sh).

They are used to generate the [system RPMs on releases page](https://github.com/ParallelSSH/ssh2-python/releases), which all link against system libssh2.
