### ISSUE TITLE
Doc: Please provide an example for continuous data reading

### ISSUE THREAD

**Issue by The-Loeki** [ParallelSSH/ssh2-python#32]
Thank you for an awesome library, havin' fun with it now ;)

The one thing I can't seem to figure out is how to do the equivalent of 
`ssh -t myhost 'less +F /var/log/messages'`

(as in, allocate a TTY and keep feeding the command output into it)

would you be so kind as to provide an example on how to do something like that?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

That is pretty easy:

```
<make session>
chan = session.open_session()
chan.pty()
chan.execute('less -F /var/log/messages')
size, data = chan.read()
while size > 0:
    <..>
    if <break condition>:
        break
    size, data = chan.read()
chan.close()
session.disconnect()
```

Reading will never complete with a command like that, so will need to break out of the loop after some break condition, or use non-blocking mode with a timeout.

PRs welcome for a complete example.

**Comment by pkittenis** [comment]
See [non-blocking example](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/nonblocking_execute.py). PRs with somplete examples welcome.

**Comment by pkittenis** [comment]
Examples exist for similar code.
