### ISSUE TITLE
userauth_password takes a long time and not ending

### ISSUE THREAD

**Issue by qlygirl** [ParallelSSH/ssh2-python#33]
here is my code:

```
_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
_sock.settimeout(10)
_sock.connect((my_host, 22))

s = Session()
s.handshake(_sock)

s.userauth_password('root', str(my_password))
```

**Comment by pkittenis** [comment]
Try the [password auth example script](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/password_auth.py), does that work for you? 

If so, it is more likely a problem in client code or server configuration. Would also suggest to check server logs and that password auth is allowed (see `session.userauth_list`).

**Comment by qlygirl** [comment]
your are right, problem in server, thanks for your help.
