### ISSUE TITLE
Damaged session if direct_tcpip channel open fails

### ISSUE THREAD

**Issue by gpb536** [ParallelSSH/ssh2-python#34]
```
import socket
from ssh2.session import Session
from ssh2.listener import *

username='user'
passwd='password'
serverA='myServerA'
serverB='doesNotExist'

#open socket connection
sock = socket.socket(socket.IF_INET, socket.SOCK_STREAM)
sock.connect((serverA, 22))

#open session and authenticate
session = Session()
session.handshake(sock)
session.userauth_password(username, passwd)
session.set_timeout(2000)

#demonstrate successful channel open and execute command on serverA
chan = session.open_session()
if chan:
    print('successfully opened channel with serverA')
    chan.execute('ls')
    chan.close()
else:
    print('Failed to open channel with serverA')

#Try to open direct tcpip channel, via serverA SSH tunnel, to unreachable serverB
direct_chan = session.direct_tcpip(serverB, 22)
if direct_chan:
    print('ServerB was reached')
else:
    print('ServerB was unreachable')

#Cannot now open channel with serverA - why???
chan = session.open_session()
if chan:
    print('successfully opened channel with serverA')
    chan.execute('ls')
    chan.close()
else:
    print('Failed to open channel with serverA')

session.disconnect()
sock.close()
```

__Expected behaviour:__ 
Assume serverA is a reachable SSH server, and serverB is unreachable.  You successfully open a channel and execute a command on serverA.  With the same session, you try to open a tunneled direct_tcpip connection to an unreachable serverB.  The direct_tcpip channel fails as expected.  I would then still expect to be able to use the same session to sucessfully open a channel and execute a command  on serverA a second time

__Actual behaviour:__ 
The second time you try to open a channel to serverA to execute a command, the open_session fails.  It's like the session has been damaged by the failure to open the direct_tcpip connection to serverB. 

Note that if serverB is reachable, then the session is still ok, and you can still open a channel to serverA and execute a command.

Why does this happen and is there a fix?  I want to continue using a session for communication with serverA even if serverB is unreachable.

( Not sure if my SSH session/channel terminology is exactly correct, but hopefully my meaning is clear from the code )

**Comment by pkittenis** [comment]
What version of `ssh2-python` is being used? It must be out of date as channel failures now raise exceptions rather than returning `None`.

Cannot replicate with latest release, `0.15.0`:

```
from __future__ import print_function

import socket
import os
import pwd

from ssh2.session import Session

USERNAME = pwd.getpwuid(os.geteuid()).pw_name

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(('localhost', 22))
s = Session()
s.handshake(sock)
s.agent_auth(USERNAME)

chan = s.open_session()
chan.execute('echo me')
size, data = chan.read()
while size > 0:
    print(data)
    size, data = chan.read()
chan.close()

try:
    d_chan = s.direct_tcpip('fakey', 22)
except Exception:
    pass
else:
    raise Exception("Should have failed")

chan = s.open_session()
chan.execute('echo me')
size, data = chan.read()
while size > 0:
    print(data)
    size, data = chan.read()
chan.close()
s.disconnect()
sock.close()
```

Output:

```
me

me
```

**Comment by gpb536** [comment]
Agh you're correct.  I was running 0.6.  Seems to work ok in 0.15.0

**Comment by gpb536** [comment]
Thanks, I'm using 0.15 now.  I have more information.  Your example does not work for me when the server for the direct_tcpip connection ("fakey" in your example) is a real server **behind a firewall**.  In that case, the code waits indefinitely when trying to open the direct channel.

I tried adding a timeout to the session (s.set_timeout(10000)).  After the timeout occurs during the opening of the direct_tcpip channel, the session is unusable (the second s.open_session() fails).

I don't have a full understanding of what is happening under the hood.  When opening a direct_tcpip channel, I presume that within the underlying libssh2 library a new socket connection between 'localhost' and 'fakey' is created.... how is the timeout for that new connection set?  It seems like there isn't a timeout.

**Comment by pkittenis** [comment]
The SSH protocol implementation, and this is in libssh2 code, is to open a new channel on the same socket for the direct tcp/ip connection. This is no different than any other channel, like `open_session()`, so should work the same way.

As far as I can see, using socket timeout also requires session to have same timeout and therefore be in non-blocking mode. In the below test case after a timeout occurs, the session will raise `Timeout` continuously and has to be restarted, ie re-authenticate:

```python
from __future__ import print_function

import socket
import os
import pwd

from ssh2.session import Session
from ssh2.error_codes import LIBSSH2_ERROR_EAGAIN
from ssh2.utils import wait_socket

USERNAME = pwd.getpwuid(os.geteuid()).pw_name

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(('localhost', 22))
s = Session()
s.handshake(sock)
s.agent_auth(USERNAME)

sock.settimeout(1000)
s.set_timeout(1000)

chan = s.open_session()
while chan == LIBSSH2_ERROR_EAGAIN:
    wait_socket(sock, s)
    chan = s.open_session()
while chan.execute('echo me') == LIBSSH2_ERROR_EAGAIN:
    wait_socket(sock, s)
while chan.wait_eof() == LIBSSH2_ERROR_EAGAIN:
    wait_socket(sock, s)
size, data = chan.read()
while size == LIBSSH2_ERROR_EAGAIN:
    wait_socket(sock, s)
    size, data = chan.read()
while size > 0:
    print(data)
    size, data = chan.read()

tries = 0
try:
    d_chan = s.direct_tcpip('google.com', 5555)
    while d_chan == LIBSSH2_ERROR_EAGAIN:
        wait_socket(sock, s, timeout=.1)
        d_chan = s.direct_tcpip('google.com', 5555)
        tries += 1
    if tries > 2:
        raise Exception
except Exception:
    pass
else:
    raise Exception("Should have failed")

# Raises timeout immediately
chan = s.open_session()
chan.close()
s.disconnect()
sock.close()
```

This looks like an issue in libssh2 and there is one [similar issue](https://github.com/libssh2/libssh2/issues/232) about channel blocking indefinitely after a timeout that looks related. Would be worth making a test case in C when there is some time.

**Comment by pkittenis** [comment]
Not seeing anything that needs changing in ssh2-python.
