### ISSUE TITLE
feature request - certificate based authentication

### ISSUE THREAD

**Issue by saifhhasan** [ParallelSSH/ssh2-python#39]
ssh2-python + parallel-ssh provides very promising performance results for our usecase of running thousands of commands remotely. However in our particular usecase authentication must happen via certificate. Are there any plans for adding it in ssh2-python.

Because of this we are stuck with paramiko, buggy and poor performer, because it has support for ssh certificates.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest!

This project provides python bindings for libssh2 and feature requests like this one should be made at libssh2. I would suggest creating this at [the libssh2 github repo](https://github.com/libssh2/libssh2) - there is no existing feature request for certificate authentication yet from what I can see. Creating one should help spark interest - I am also interested in it.

For supporting certificate authentication in `parallel-ssh` specifically, the current major feature work is for making a `libssh` (no relation) based client via the [ssh-python](https://github.com/ParallelSSH/ssh-python) bindings, which does support certificate authentication as well as kerberos (GSS-API), which `libssh2` currently does not support either. That client will, however, only support authentication and `run_command` initially as not all of the `libssh` API can be used non-blocking. It follows that it will not be the default client either.

Feel your pain with paramiko. Its leaves a lot to be desired from, implementation, is a major inspiration for writing bindings from scratch for now two different C libraries and clients for them in `parallel-ssh`. I very much look forward to not having to use nor support paramiko post parallel-ssh `2.0.0`.

Can [watch this issue](https://github.com/ParallelSSH/parallel-ssh/issues/135) for tracking the libssh client implementation. It is not too far off and currently scheduled for the `1.10.0` release, but no timelines are provided - these are all "free" time projects. Contributions always welcome.
