### ISSUE TITLE
Public key example incorrect

### ISSUE THREAD

**Issue by sganis** [ParallelSSH/ssh2-python#41]
Minor issue, the public key example in the readme is incorrect:
this:
```
session.userauth_publickey_fromfile(
    username, 'my_pkey.pub', 'my_pkey', '')
```
shouldn't it be like this?
```
session.userauth_publickey_fromfile(
    username, 'pkey', 'optional pkey.pub' , 'optional passphrase')
```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest and report. Yes, the API was changed in a subsequent release to make passphrase optional. Do you want to make a PR for it?

**Comment by pkittenis** [comment]
Resolved in [latest commit](https://github.com/ParallelSSH/ssh2-python#public-key-authentication).
