### ISSUE TITLE
From source builds on system libssh2 without Cython installed

### ISSUE THREAD

**Issue by DerekTBrown** [ParallelSSH/ssh2-python#43]
### Bug reports

__Steps to reproduce:__

1. Rebuild the library using the system libssh, with the appropriate flags set (https://ssh2-python.readthedocs.io/en/latest/installation.html#system-library-build)

__Expected behaviour:__ [What was expected to happen.]
1. Expect to compile the library without the need for agent forwarding logic (ie libssh2_channel_request_auth_agent)

__Actual behaviour:__ [What actually happened.]
Yields a C warning and a runtime error:
```
ssh2/channel.c:6902:22: warning: implicit declaration of function 'libssh2_channel_request_auth_agent' [-Wimplicit-function-declaration]
           __pyx_v_rc = libssh2_channel_request_auth_agent(__pyx_v_self->_channel);
```

Very clearly, this function still occurs in the generated output:
https://github.com/ParallelSSH/ssh2-python/blob/2d62505a472f3e4e7d023186bf788153f85b35ab/ssh2/channel.c#L6902

**Comment by DerekTBrown** [comment]
Also being reported by someone else:
https://bugzilla.redhat.com/show_bug.cgi?id=1631978

**Comment by DerekTBrown** [comment]
Can someone also explain the logic behind hard-forking libssh2 to create the package?

**Comment by pkittenis** [comment]
From source builds with `HAS_AGENT_FWD=0` require cython to be installed - documentation is lacking. Can use that to work around for now.

It would be best to switch `HAS_AGENT_FWD` to default to off, and the pre-generated C files to not include it, so that from source builds can work with system libssh2 packages. Might remove it entirely until it is merged upstream.

PRs welcome, or can watch this issue.

I'd also point you to the [Code of Conduct](https://github.com/ParallelSSH/ssh2-python/blob/master/.github/code_of_conduct.md#our-standards). Keep discussions respectful and manners matter when asking things of open source projects.

**Comment by DerekTBrown** [comment]
> Hello Derek,
> I've been able to run "password_auth.py" after some changes in "channel.c":
> At 3 different places I included :
> `#ifdef HAVE_AGENT_FWD #endif`
> lines: L1261, L6861->L6962 and L7168
> Do you think it will be useful tu make a "pull request"?
> I haven't tested the changes very well yet, so it may be useful to perform more extensive testing before including these modifications into a package.

@JoelStienlet those are auto-generated files, so a PR cannot be made against those files directly.

**Comment by DerekTBrown** [comment]
I think this is more a versioning problem than anything else.  If you look into the original source of @JoelStienlet's bug, it is because Red Hat's auto build of this package is silently failing due to the jump to the embedded lib.  Most downstream projects don't get a choice of which version of `libssh` to build against.

My suggestion would be to;
- Default to `EMBEDDED_LIB=0` and `HAVE_AGENT_FORWARD=0`
- Move all code requiring a non-system version of libssh (`ie >= 1.4.2`) to a feature fork.
- Release multiple versions of the app like `ssh2-python` and `ssh2-python-next`

**Comment by DerekTBrown** [comment]
@pkittenis even with Cython installed, there is still an issue with `HAVE_AGENT_FORWARD`.  The Cython method cache is really stubborn, so it won't regenerate the extension unless you manually invalidate the cache.

**Comment by DerekTBrown** [comment]
I am still having issues even with Cython installed.  It seems Cython's cache is very simplistic, and so it is not overwriting the generated C files.

**Comment by pkittenis** [comment]
The existing C files will need to be deleted. Can always use the [pre-built RPMs on releases page](https://github.com/ParallelSSH/ssh2-python/releases/tag/0.15.0.post9).

No, the embedded source code will not be moved to feature branch, nor will a new package be made just for that.

Most downstream projects use binary wheels, which require bundled libssh2. These are already published.

From source builds have a choice to use either bundled or system libssh2. `EMBEDDED_LIB=1` means libssh2 >= 1.6.0 features, has nothing to do with linking - [per docs](https://ssh2-python.readthedocs.io/en/latest/installation.html#system-library-build).

Adjusting this means re-generating cython files - there is no other option short of dropping support for < 1.6.0. Cython does not have support for custom `ifdef` in its generated C code.

Which library to build against can be adjusted for from source builds with the standard `-I <..> -R <..>` arguments - [see instructions](https://ssh2-python.readthedocs.io/en/latest/installation.html#custom-build).

**Comment by DerekTBrown** [comment]
Sorry for the confusion- I made a lot of assumptions that features existed (ie `ifdef`, bundling cross-packages), which I guess Cython just doesn't support.

The usecase that it seems both @JoelStienlet and I have is to do a from source build against the system version libssh without Cython installed.  One option would be to add a deploy script to one of the CI tools to build a tarball with pre-compiled C for `EMEBEDDED_LIB=0`, `HAS_AGENT_FWD=0`.  Does that seem like a reasonable solution?

**Comment by pkittenis** [comment]
Yes, the above is needed to re-generate cython files. The same is done [for building on Windows](https://github.com/ParallelSSH/ssh2-python/blob/master/.appveyor.yml#L126) which also needs it.

The approach being taken is to bundle libssh2 source code, not as a submodule, and target upstream master branch by default. See [this branch](https://github.com/ParallelSSH/ssh2-python/tree/bundled_ssh2).

This will allow system libssh2 builds without cython or re-generating C files, as well as allow the library to be installed from an sdist and use a more recent version of libssh2 which is needed to connect to more recent servers.

**Comment by JoelStienlet** [comment]
Hello Pan and Derek,
I noticed that versioneer tries to open 
/usr/lib64/python2.7/site-packages/ssh2_python-0.15.0.post9+1.g2d62505.dirty-py2.7-linux-x86_64.egg/.git/HEAD
when the library is loaded (doing an "strace -e trace=file -f" ).

-> Shouldn't "setup.py install" install this file?
I can copy it manually, but it would certainly be more elegant if it were installed automatically from setup.py.

Another point: versioneer executes /usr/bin/git on runtime. The test script still works if I remove /usr/bin/git. But that seems to imply that the runtime behaviour of versioneer may depend on the presence or not of git. 
-> The question is: is there an option to define the version statically on install, so that versioneer doesn't attempt to run git on runtime?

Sorry if my questions are not relevant, I've never used versioneer before, I'm discovering the tool.

**Comment by pkittenis** [comment]
Hi,

No, `.git/HEAD` should not be included, nor does versioneer use it for versioning of distributed files. It always attempts to load it and run git, but for distribution files git is not required and it always uses a static version that was built at `sdist` or `bdist` creation time.

For example the wheel above contains a file `ssh2/_version.py` which has static version data taken from the git tag of when the wheel was built. There is actually [a pending PR from myself](https://github.com/warner/python-versioneer/pull/171) to get a change merged upstream to do that correctly for wheels with extensions which this repo is using. 

Related to this, there is a [fix_version.py](https://github.com/ParallelSSH/ssh2-python/blob/master/ci/appveyor/fix_version.py) to generate this file prior to deleting and re-generating cython files as that would change the version number. This is used for windows wheels and system package builds which change compile time env flags.

Moving forward it would be best to migrate to `setuptools_scm` which is the new standard way of doing versioning from git information - versioneer does not seem to be maintained anymore. Low priority though and is not related to this issue.

**Comment by DerekTBrown** [comment]
@pkittenis thanks for the resolution on this.  This is workable.

> Yes, the above is needed to re-generate cython files. The same is done [for building on Windows](https://github.com/ParallelSSH/ssh2-python/blob/master/.appveyor.yml#L126) which also needs it.
> 
> The approach being taken is to bundle libssh2 source code, not as a submodule, and target upstream master branch by default. See [this branch](https://github.com/ParallelSSH/ssh2-python/tree/bundled_ssh2).
> 
> This will allow system libssh2 builds, with a new env flag, without cython or re-generating C files, as well as allow the library to be installed from an sdist using a bundled libssh2 (no dependency) and use a more recent version of libssh2 which is needed to connect to more recent servers.
