### ISSUE TITLE
keyboard-interactive authentication

### ISSUE THREAD

**Issue by pr0pane23** [ParallelSSH/ssh2-python#58]
Do you have any plans to implement this functionality? 

Some systems e.g. FreeBSD use this for a simple username/password authentication and do not use the 'password' method. I have tried authenticating with 'userauth_password' but it fails  with an 'Unrecognized authentication method: password' error.

Cheers

pr0pane

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. 

For completeness, yes, the intention is to implement all of the API. This one looks pretty simple, PRs always welcome.

**Comment by dvolodin7** [comment]
I've filled an PR #76

**Comment by pkittenis** [comment]
Done by #76
