### ISSUE TITLE
Cut command output

### ISSUE THREAD

**Issue by godrix** [ParallelSSH/ssh2-python#60]
The output of the command has more than 110 lines and ends up cutting the output, when I use the while execution hangs, is there any way out? How to make channel.read () read only the last line of the output?

```
#start interface shell in the channel
channel.shell()

channel.write("config\n")
channel.write("show service-port gpon match vlan vlan-id any\n")
time.sleep(1)
size, data = channel.read()
while size > 0:
    print(data)
    size, data = channel.read()
channel.close()
print("Exit status {0}".format(channel.get_exit_status()))
````

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. 

See [execution example](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/example_echo.py) on how to correctly wait for a command to finish. If the channel is closed before command has finished, output will be truncated. Not an issue with library - closing.
