### ISSUE TITLE
Local port forwarding example

### ISSUE THREAD

**Issue by jjsp556** [ParallelSSH/ssh2-python#61]
Could an example be posted to the Examples directory of how one would go about performing local port forwarding? The OpenSSH command I'd like to replicate is as follows:

ssh -L LOCALPORT:HOST2:DESTINATIONPORT HOST1

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. This is non-trivial - PRs welcome. There is such implementation in `parallel-ssh` if looking for a ready-made solution. See [API documentation]((https://parallel-ssh.readthedocs.io/en/latest/tunnel.html).

**Comment by Red-M** [comment]
I've tried to do this and I can say it is very hard to do.

I've run into some performance issues in doing this that seem to be unavoidable and I'd love a non gevent version of the parallel-ssh implementation that I can run with just pure threads.

I tried to do it but I get 1 thread burning CPU cycles on a single core. I've debugged my code and I can't locate why it is doing this.

**Comment by pkittenis** [comment]
As above, it is non trivial. If its burning cycles that probably means a missing select calls somewhere, or a select that returns 0 with no check leading to hot loop. Paramiko is not relevant - different API. There is also a C code example at libssh2 documentation.

**Comment by Red-M** [comment]
Both threads for:

- reading from the downstream socket and writing to the ssh channel
- reading from the ssh channel and writing to the downstream socket

are in a blocked state for my testing. 

Paramiko is using in it's example of port forwarding, `select.select()` which could be compatible from my testing by implementing a `chan.fileno()` function to allow the builtin `select.select()` to work as [per the example](https://github.com/paramiko/paramiko/blob/master/demos/forward.py#L55-L100) by replacing line 58 with the ssh2-python's own channel object with the addition suggested above.

However I'd ideally want this in C rather than in Python code.

**Comment by pkittenis** [comment]
C [code example here](https://libssh2.org/examples/direct_tcpip.html). Paramiko is not relevant.

For a working implementation see parallel-ssh (note select is used, as is a separate thread). Usual libssh2 rules apply - cannot share sessions/channels across threads. Not surprising if it is getting blocked when the code is attempting to read and write from the same channel in different threads.

**Comment by Red-M** [comment]
They work but block later on.
I've even done this:
`#!/usr/bin/env python3
import collections
import time
import threading



from threading import Thread, Event
import logging

from gevent import socket, spawn, joinall, get_hub, sleep
from gevent.select import select

from ssh2.error_codes import LIBSSH2_ERROR_EAGAIN

from pssh.clients.native.single import SSHClient
from pssh.constants import DEFAULT_RETRIES, RETRY_DELAY


logger = logging.getLogger(__name__)



class Tunnel(Thread):
    """SSH proxy implementation with direct TCP/IP tunnels.
    Each tunnel object runs in its own thread and can open any number of
    direct tunnels to remote host:port destinations on local ports over
    the same SSH connection.
    To use, append ``(host, port)`` tuples into ``Tunnel.in_q`` and read
    listen port for tunnel connection from ``Tunnel.out_q``.
    ``Tunnel.tunnel_open`` is a *thread* event that will be set once tunnel is
    ready."""

    def __init__(self, host, in_q, out_q, user=None,
                 password=None, port=None, pkey=None,
                 num_retries=DEFAULT_RETRIES,
                 retry_delay=RETRY_DELAY,
                 allow_agent=True, timeout=None,
                 channel_retries=5):
        """
        :param host: Remote SSH host to open tunnels with.
        :type host: str
        :param in_q: Deque for requesting new tunnel to given ``((host, port))``
        :type in_q: :py:class:`collections.deque`
        :param out_q: Deque for feeding back tunnel listening ports.
        :type out_q: :py:class:`collections.deque`
        :param user: (Optional) User to login as. Defaults to logged in user
        :type user: str
        :param password: (Optional) Password to use for login. Defaults to
          no password
        :type password: str
        :param port: (Optional) Port number to use for SSH connection. Defaults
          to ``None`` which uses SSH default (22)
        :type port: int
        :param pkey: Private key file path to use. Note that the public key file
          pair *must* also exist in the same location with name ``<pkey>.pub``
        :type pkey: str
        :param num_retries: (Optional) Number of connection and authentication
          attempts before the client gives up. Defaults to 3.
        :type num_retries: int
        :param retry_delay: Number of seconds to wait between retries. Defaults
          to :py:class:`pssh.constants.RETRY_DELAY`
        :type retry_delay: int
        :param timeout: SSH session timeout setting in seconds. This controls
          timeout setting of authenticated SSH sessions.
        :type timeout: int
        :param allow_agent: (Optional) set to False to disable connecting to
          the system's SSH agent.
        :type allow_agent: bool
        """
        Thread.__init__(self)
        self.client = None
        self.session = None
        self._sockets = []
        self.in_q = in_q
        self.out_q = out_q
        self.host = host
        self.port = port
        self.user = user
        self.password = password
        self.pkey = pkey
        self.num_retries = num_retries
        self.retry_delay = retry_delay
        self.allow_agent = allow_agent
        self.timeout = timeout
        self.exception = None
        self.tunnel_open = Event()
        self._tunnels = []
        self.channel_retries = channel_retries

    def __del__(self):
        self.cleanup()

    def _read_forward_sock(self, forward_sock, channel):
        while True:
            if channel.eof():
                logger.debug("Channel closed")
                return
            try:
                data = forward_sock.recv(1024)
            except Exception:
                logger.exception("Forward socket read error:")
                sleep(1)
                continue
            data_len = len(data)
            if data_len == 0:
                continue
            data_written = 0
            while data_written < data_len:
                try:
                    rc, bytes_written = channel.write(data[data_written:])
                except Exception:
                    logger.exception("Channel write error:")
                    sleep(1)
                    continue
                data_written += bytes_written
                if rc == LIBSSH2_ERROR_EAGAIN:
                    select((), ((self.client.sock,)), (), timeout=0.001)

    def _read_channel(self, forward_sock, channel):
        while True:
            if channel.eof():
                logger.debug("Channel closed")
                return
            try:
                size, data = channel.read()
            except Exception as ex:
                logger.error("Error reading from channel - %s", ex)
                sleep(1)
                continue
            while size == LIBSSH2_ERROR_EAGAIN or size > 0:
                if size == LIBSSH2_ERROR_EAGAIN:
                    select((self.client.sock,), (), (), timeout=0.001)
                    try:
                        size, data = channel.read()
                    except Exception as ex:
                        logger.error("Error reading from channel - %s", ex)
                        sleep(1)
                        continue
                while size > 0:
                    try:
                        forward_sock.sendall(data)
                    except Exception as ex:
                        logger.error(
                            "Error sending data to forward socket - %s", ex)
                        sleep(.5)
                        continue
                    try:
                        size, data = channel.read()
                    except Exception as ex:
                        logger.error("Error reading from channel - %s", ex)
                        sleep(.5)

    def _init_tunnel_sock(self,lport):
        tunnel_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        tunnel_socket.settimeout(self.timeout)
        tunnel_socket.bind(('127.0.0.1', lport))
        tunnel_socket.listen(0)
        listen_port = tunnel_socket.getsockname()[1]
        self._sockets.append(tunnel_socket)
        return tunnel_socket, listen_port

    def _init_tunnel_client(self):
        self.client = SSHClient(self.host, user=self.user, port=self.port,
                                password=self.password, pkey=self.pkey,
                                num_retries=self.num_retries,
                                retry_delay=self.retry_delay,
                                allow_agent=self.allow_agent,
                                timeout=self.timeout,
                                _auth_thread_pool=False)
        self.session = self.client.session
        self.tunnel_open.set()

    def cleanup(self):
        for _sock in self._sockets:
            if not _sock:
                continue
            try:
                _sock.close()
            except Exception as ex:
                logger.error("Exception while closing sockets - %s", ex)
        if self.session is not None:
            self.client.disconnect()

    def _consume_q(self):
        while True:
            try:
                lport, host, port = self.in_q.pop()
            except IndexError:
                sleep(1)
                continue
            logger.debug("Got request for tunnel to %s:%s", host, port)
            tunnel = spawn(self._start_tunnel, host, port, lport)
            self._tunnels.append(tunnel)

    def _open_channel(self, fw_host, fw_port, local_port):
        channel = self.session.direct_tcpip_ex(
            fw_host, fw_port, '127.0.0.1',
            local_port)
        while channel == LIBSSH2_ERROR_EAGAIN:
            select((self.client.sock,), (self.client.sock,), ())
            channel = self.session.direct_tcpip_ex(
                fw_host, fw_port, '127.0.0.1',
                local_port)
        return channel

    def _open_channel_retries(self, fw_host, fw_port, local_port,
                              wait_time=0.1):
        num_tries = 0
        while num_tries < self.channel_retries:
            try:
                channel = self._open_channel(fw_host, fw_port, local_port)
            except Exception:
                num_tries += 1
                if num_tries > self.num_retries:
                    raise
                logger.error("Error opening channel to %s:%s, retries %s/%s",
                             fw_host, fw_port, num_tries, self.num_retries)
                sleep(wait_time)
                wait_time *= 5
                continue
            return channel

    def _start_tunnel(self, fw_host, fw_port, lport):
        try:
            listen_socket, listen_port = self._init_tunnel_sock(lport)
        except Exception as ex:
            logger.error("Error initialising tunnel listen socket - %s", ex)
            self.exception = ex
            return
        logger.debug("Tunnel listening on 127.0.0.1:%s on hub %s",
                     listen_port, get_hub().thread_ident)
        self.out_q.append(listen_port)
        try:
            forward_sock, forward_addr = listen_socket.accept()
        except Exception as ex:
            logger.error("Error accepting connection from client - %s", ex)
            self.exception = ex
            listen_socket.close()
            return
        forward_sock.settimeout(self.timeout)
        logger.debug("Client connected, forwarding %s:%s on"
                     " remote host to %s",
                     fw_host, fw_port, forward_addr)
        local_port = forward_addr[1]
        try:
            channel = self._open_channel_retries(fw_host, fw_port, local_port)
        except Exception as ex:
            logger.exception("Could not establish channel to %s:%s:",
                             fw_host, fw_port)
            self.exception = ex
            forward_sock.close()
            listen_socket.close()
            return
        source = spawn(self._read_forward_sock, forward_sock, channel)
        dest = spawn(self._read_channel, forward_sock, channel)
        logger.debug("Waiting for read/write greenlets")
        self._wait_send_receive_lets(source, dest, channel, forward_sock)

    def _wait_send_receive_lets(self, source, dest, channel, forward_sock):
        try:
            joinall((source, dest), raise_error=True)
        except Exception as ex:
            logger.error(ex)
        finally:
            logger.debug("Closing channel and forward socket")
            channel.close()
            forward_sock.close()

    def run(self):
        """Thread run target. Starts tunnel client and waits for incoming
        tunnel connection requests from ``Tunnel.in_q``."""
        try:
            self._init_tunnel_client()
        except Exception as ex:
            # logger.error("Tunnel initilisation failed - %s", ex)
            self.exception = ex
            return
        logger.debug("Hub ID in run function: %s", get_hub().thread_ident)
        consume_let = spawn(self._consume_q)
        try:
            consume_let.get()
        except Exception as ex:
            logger.error("Tunnel thread caught exception and will exit:",
                         exc_info=1)
            self.exception = ex
        finally:
            self.cleanup()


def main():
    host = '192.168.0.151'
    in_q = collections.deque()
    out_q = collections.deque()
    client = Tunnel(host,in_q,out_q)

    in_q.append((2222,'google.com',80))

    tun_thread = threading.Thread(target=client.run)
    tun_thread.daemon = True
    # tun_thread.name = option_string
    tun_thread.start()

    while len(out_q)==0:
        # print(out_q)
        pass
    port = out_q.pop()
    print(port)
    time.sleep(30)



if __name__=='__main__':
    main()
`

and I still get the same CPU chewing as my own dual threaded code.

**Comment by pkittenis** [comment]
For reference:

* Copyrighted code may not be used without copyright information intact
* Derivative works of open source licensed code **must** be distributed under a compatible license with copyright information intact

For issues regarding tunnelling implementation in parallel-ssh, an issue should be raised on that project. This is an issue tracker for ssh2-python, not for debugging ad-hoc or derivative works of this or any other project.

When there is working code for this issue that can be reviewed, a PR may be raised.

**Comment by Red-M** [comment]
Not interested in providing a PR anymore, sorry.

**Comment by Red-M** [comment]
Hey, sorry about all that, I haven't been feeling the best.

I've got a working implementation that should still be reasonably fast but I would like to confirm with you first if it is ok to release. I've had to rewrite a few functions since my project doesn't use gevents.

I could contribute a working example for ssh2-python from such code.

My project uses a Linux kernel style GPL2 license.

**Comment by pkittenis** [comment]
Hi,

If it's a from scratch implementation there is no need to check with me. If it is based on parallel-ssh code then a compatible license must be used, as well as copyright info retained but as long as that is done the license allows modifications as well as distribution. Both projects are LGPL v2.1 only which allows distribution as GPLv2 only (not later) per GNU license [compatibility matrix](https://www.gnu.org/licenses/gpl-faq.html#gpl-compat-matrix).

If it resolves the performance issue when a client connects - which I've seen too - can consider contributing the changes to parallel-ssh as well, or I can back port them separately. Thanks for considering to contribute.

**Comment by Red-M** [comment]
I've got similar implementations for eagain wrappers (read, write and generic functions) that were based from yours. I've kept the copyright for that in just those functions as the rest is either my own or another MIT project.
The local tunneling is from paramiko but using eagain wrappers that I mentioned from before.

A sample:
```python
    def _block(self, func, *args, **kwargs):
        # This function was part of parallel-ssh and has been modified to work with RedSSH.
        #
        # Copyright (C) 2014-2018 Panos Kittenis.
        #
        # This library is free software; you can redistribute it and/or
        # modify it under the terms of the GNU Lesser General Public
        # License as published by the Free Software Foundation, version 2.1.
        #
        # This library is distributed in the hope that it will be useful,
        # but WITHOUT ANY WARRANTY; without even the implied warranty of
        # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
        # Lesser General Public License for more details.
        #
        # You should have received a copy of the GNU Lesser General Public
        # License along with this library; if not, write to the Free Software
        # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
        out = func(*args, **kwargs)
        while out==LIBSSH2_ERROR_EAGAIN:
            self._block_select()
            out = func(*args, **kwargs)
        return(out)
```

**Comment by pkittenis** [comment]
Thanks, but that's too small to need attribution. There's similar code in examples which are without copyright. 

So the tunnelling is using paramiko with ssh2-python to connect to remote host via the tunnel I suppose. That's not using ssh2-python for the tunnel so I don't see what example could be added here for that.

**Comment by Red-M** [comment]
I used Paramiko's structure for the `select.select()` so that it could be contained in a single thread instead of requiring two threads.

If you're fine with the other 3 functions that handle `LIBSSH2_ERROR_EAGAIN` for all my other calls to work, I can remove that statement from them.

**Comment by pkittenis** [comment]
These are clearly derived from parallel-ssh, which makes that work a derivative. So usual copyright and license terms apply. If it was just the one function which is pretty general I wouldn't care.

License cannot be applied to blocks of code like that - if the project uses or is derived from licensed code it must be distributed in a compatible license as a whole. See above link for compatibility.

Any further discussion on this can be done on mail group - this issue is for tracking the forwarding example progress.

**Comment by Red-M** [comment]
Yeah, I use GPL2 but with a linux kernel style header so this should be fine.
I'm just unsure if I need to remove these notices all together.

**Comment by Red-M** [comment]
I've released a working implementation under one of my projects here:
https://github.com/Red-M/RedSSH/blob/master/redssh/tunneling.py#L75-L115

The only bug here is that it is nearly impossible to tell if the client has disconnected from the local socket so I've put a timeout on that to release the thread spawned from that.

**Comment by Red-M** [comment]
So I've recently got this working in my library rather well and it requires a lot of work to get this working correctly.

**Comment by pkittenis** [comment]
Local port forward is done in [parallel-ssh](https://github.com/ParallelSSH/parallel-ssh) using ssh2-python.
