### ISSUE TITLE
Update publickey authentication from file example

### ISSUE THREAD

**Issue by thomasd3** [ParallelSSH/ssh2-python#62]
I found ssh2-python after trying to use Paramiko to log in using a new OpenSSH key and realizing it doesn't support that format.

The keys start with: -----BEGIN OPENSSH PRIVATE KEY-----

Would it be possible to get an example to start a session using one of these keys and executing a command on a remote machine?

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

For usage questions best to ask on mail group - this is an issue tracker.

See documentation on [userauth_publickey_fromfile](https://ssh2-python.readthedocs.io/en/latest/session.html#ssh2.session.Session.userauth_publickey_fromfile). 

If there is a problem, raise an issue with code and steps to reproduce.

There is also an [example on the above](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/publickey_fromfile.py) which needs updating. PRs welcome.

**Comment by pkittenis** [comment]
Example updated.
