### ISSUE TITLE
Question regarding the File type 

### ISSUE THREAD

**Issue by dvm-shlee** [ParallelSSH/ssh2-python#64]
Hi, Thank you for the wonderful library, I'm integrating all my code from paramilo to this library due to it's fast and intuitive way to use!

Just one thing that I couldn't figure out for integration is the way to check the remote file type using such as LIBSSH2_SFTP_S_IFDIR. The main idea is make a replica of
os.path.isdir() for remote server.

I'm trying to use fstat to find the way, but since Im nor familer with libssh2,
struggling to find it out, so hope to ask if there is any simple way to do this using your library.

Thanks!

**Comment by dvm-shlee** [comment]
Oh just figure out, 

```
from ssh2 import sftp
import stat

path = '/tmp/foldername'
fstat = sftp.lstat(path)
stat.S_ISDIR(fstat.permissions) # check isdir
stat.S_ISREG(fstat.permissions) # check isfile
stat.filemode(fstat.permissions) # return file permission mode as a string: '-rwxrw-rw-'
```

Thank you for your great work!! this is an amazing library!

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. For usage questions best to ask on [mail group](https://groups.google.com/forum/#!forum/ssh2-python) - this is a tracker for active bugs/feature requests. 

The way this is done in [parallel-ssh](https://github.com/ParallelSSH/parallel-ssh) ([copy_remote_file](https://parallel-ssh.readthedocs.io/en/latest/native_single.html#pssh.clients.native.single.SSHClient.copy_remote_file)) is by using `sftp.opendir` and checking if it raises error. Error means it's a file, no error means it's a dir. There may be other ways.
