### ISSUE TITLE
sftp.open is terribly slow

### ISSUE THREAD

**Issue by mflage** [ParallelSSH/ssh2-python#66]
I have attempted to use ssh2-python to upload large files to an ssh server, but I find that there is something terribly broken here. I'm using version 0.17.0 installed using 'pip' and the example script provided just to get stuff working. Using 'sftp' or 'scp' gives me throughput at around 200-300 Mbps, whereas ssh2-python gives me around 100 Kbps... I thought this was supposed to be fast?

Trying the scp example yields better results, averaging at 27 MB/s.

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. In short, use SCP.

libssh2 [has a known issue](https://github.com/libssh2/libssh2/issues/90) with SFTP performance. This library provides bindings to libssh2. It can only be as fast as libssh2 is. For reporting issues with this library follow issue template.
