### ISSUE TITLE
scp a directory

### ISSUE THREAD

**Issue by acerv** [ParallelSSH/ssh2-python#69]
Hello everyone,

thank you very much for this awesome library. I'm actually moving all paramiko code to ssh2-python and it's incredibly fast.

Now I'm wondering if there's a way to transfer an entire directory using SCP, as scp command does when running *scp -r*.

Best regards,
Andrea

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest, glad you found it useful. That is not natively supported by the library, no. It is up to client code to implement recursion, eg [the implementation in parallel-ssh](https://parallel-ssh.readthedocs.io/en/latest/native_single.html#pssh.clients.native.single.SSHClient.scp_recv) (also a [parallel version of it](https://parallel-ssh.readthedocs.io/en/latest/native_parallel.html#pssh.clients.native.parallel.ParallelSSHClient.scp_send)).
