### ISSUE TITLE
while size > 0 nevers exits

### ISSUE THREAD

**Issue by WHumphreys** [ParallelSSH/ssh2-python#70]
Im trying to follow the online examples and if I run the following the loop never exits. 

If I remove the while loop all is good. If the read() call is waiting then whats the point of the while. 

Similar code works fine same server with paramiko using "while not channel.recv_ready() :" etc. 

Is this a bug or by design

Code:
```
import sys
import socket

from ssh2.session import Session

SSH_SERVER_IP ="IPADDRESS"

def main():

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((SSH_SERVER_IP, 22))

    session = Session()
    session.handshake(sock)
    session.userauth_password("USERNAME", "PASSWORD")

    channel = session.open_session()

    channel.shell();

    # All I want to do here is display returned banner.

    size, data = channel.read()
    while size > 0:
        print(data.decode())         # <<<< Displays banner fine.
        size, data = channel.read()  # <<<< Sticks here on debug and never exits

    channel.close()

    print("Exit status: %s" % channel.get_exit_status())

if __name__ == '__main__':
    sys.exit(main())
```

### Bug reports

__Expected behaviour:__ Exit the while loop

__Actual behaviour:__ Didn't Exit

**Comment by qzlisb** [comment]
Or you can set session to non-block, but can't be sure to receive all data

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. This is not an issue with the library.

`channel.read` on an interactive shell (`channel.shell`) will block indefinitely if there is no output to be read - this is SSH protocol behaviour. The shell is waiting for input. As it is interactive and does not send EOF, there is no indicator no more output will be sent.

The channel should be closed before trying to read again if no more commands will be sent to it. Alternatively use `channel.execute` and `channel.wait_eof` to determine that no more output will be sent.

If all the output needed has already been received, why is the client code trying to read more data without doing anything on the channel? There will obviously be no output from it unless something is executed first.

There is functionality in the libssh2 API to check if output is available - see `session.block_directions`.

See [example](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/example_echo.py) for use of `close`, `eof` and `wait_eof`.

**Comment by WHumphreys** [comment]
Cheers. That clears things up. I did it this way following an online example that is obviously wrong.

I'm also trying to build in some simple error checking for an automated unsupervised script.

i.e.

1. Get returned data
2. Is any data returned and is it complete<< as I had it this will never be reached.
3. Check returned data is correct before sending commands. (if not exit etc)

Do again for next lot of data etc

Otherwise no returned data (as some issue occurred or its wrong) the script is stuck in an infinite loop (unless there's a timeout)

**Comment by pkittenis** [comment]
The example [is using](https://github.com/ParallelSSH/ssh2-python/blob/master/examples/example_echo.py#L39-L41) `wait_eof` and `close` before reading as described above. `read` returns 0 after these when all output has been consumed.

The example as present in the repo is correct for what it does, as above.
