### ISSUE TITLE
ssh2-python - Interactive shell

### ISSUE THREAD

**Issue by nmt1** [ParallelSSH/ssh2-python#77]
**Description:**
I need an interactive shell for sending commands based on the terminal reply.
In the example below my second command is executed but not taken any effect.
I would be very grateful if anybody can guide me in this matter.

**Code**
import socket
from ssh2.session import Session
import time

host = '192.168.1.20'
user = 'test'
password = 'test'
port = 22

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((host, port))
session = Session()
session.handshake(sock)
session.userauth_password(user, password)
channel = session.open_session()
channel.shell()  **# Interactive shell ???**

channel.write('reboot' +'\r')

size, data = channel.read()
while size > 0:
    print('data:',data.decode())
    print('size: ', size)

    test = (data.decode()).find('(Yes/no):')
    if test != -1:
        time.sleep(1)
        channel.write('yes' + '\r')  **# <-- does not take any effect in my case**
        time.sleep(1)
        break
    size, data = channel.read()

channel.close()
session.disconnect()
print("Exit status: {0}".format(channel.get_exit_status()))

**Print - terminal:**
Are you sure you want to continue? (yes/no): 
size:  212
Exit status: 0

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. For usage questions best to use the mail group.

Try `\n`. `\r` is not a thing in SSH, regardless which OS the server/client is running on.
