### ISSUE TITLE
Migrate integration tests to testsshd

### ISSUE THREAD

**Issue by pkittenis** [ParallelSSH/ssh2-python#81]
Integration tests use embedded SSH server which is limited in what it can test. Migrate to container.

Ref:
https://code.getnoc.com/infrastructure/tests/testsshd

https://code.getnoc.com/noc/noc/merge_requests/1990/diffs#0c47f52f2a6192b16db8ccde786bbca459d9c3a2_0_53

**Comment by dvolodin7** [comment]
dropbear container may be useful too: https://code.getnoc.com/infrastructure/tests/testdropbear

**Comment by pkittenis** [comment]
Lack of interest and little value added by doing this, closing.
