### ISSUE TITLE
ssh2-python not packed for python 3.8

### ISSUE THREAD

**Issue by acerv** [ParallelSSH/ssh2-python#89]
Hi,

the current 0.18.0 ssh2-python version is not packed under windows for python 3.8, so it needs to be compiled by hand when using pip. Is it possible to pre-package ssh2-python for python 3.8?

Thanks,
Andrea

**Comment by acerv** [comment]
Hi, may I help you with this ticket? I really need ssh2-python for python 3.8, especially in windows, but it looks kind of hard to compile libssh2 and zlib before ssh2-python.

I checked building scripts inside ci folder, but maybe (my 2 cents) a plain script to execute inside generic systems before running ssh2-python build might help a lot.

**Comment by elwitoldo** [comment]
Hi, first of all, I want to appreciate your work as I find this module extremely useful.
If possible can you please just provide rough estimate if and when support for 3.8 will be added? 
Many thanks!

**Comment by urscion** [comment]
Not to mention cmake doesn't detect which compilers/make programs you have. I've been struggling to attempt to build it with mingw gcc and make but it seems like it only wants to use cl and nmake.

**Comment by pkittenis** [comment]
To be released in `0.19.0`. See appveyor.yml for steps to compile.

**Comment by pkittenis** [comment]
Resolved by 0.19.0. Thank you for your patience.
