### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by Addvilz** [ParallelSSH/ssh2-python#93]
Is there any chance to see a release any time soon? `0.18.0.post1` is missing `LIBSSH2_HOSTKEY_TYPE_ECDSA_*`, `LIBSSH2_KNOWNHOST_KEY_ECDSA_*`, `LIBSSH2_KNOWNHOST_KEY_ED25519` and `LIBSSH2_HOSTKEY_TYPE_ED25519` in `libssh2/include/libssh2.h`

Also Python 3.8 support is missing as mentioned in #89

**Comment by Addvilz** [comment]
For anyone who finds the issue looking for a way to support `ecdsa-sha2-nistp256`, you can define the above constants directly in Python. See the sample code bellow for a workaround.

```python
LIBSSH2_KNOWNHOST_KEY_ECDSA_256 = (4 << 18)
LIBSSH2_KNOWNHOST_KEY_ECDSA_384 = (5 << 18)
LIBSSH2_KNOWNHOST_KEY_ECDSA_521 = (6 << 18)
LIBSSH2_KNOWNHOST_KEY_ED25519 = (7 << 18)

LIBSSH2_HOSTKEY_TYPE_ECDSA_256 = 3
LIBSSH2_HOSTKEY_TYPE_ECDSA_384 = 4
LIBSSH2_HOSTKEY_TYPE_ECDSA_521 = 5
LIBSSH2_HOSTKEY_TYPE_ED25519 = 6

# ...

host_key, key_type = session.hostkey()
server_key_type = None

if key_type == LIBSSH2_HOSTKEY_TYPE_RSA:
    server_key_type = LIBSSH2_KNOWNHOST_KEY_SSHRSA
elif key_type == LIBSSH2_HOSTKEY_TYPE_DSS:
    server_key_type = LIBSSH2_KNOWNHOST_KEY_SSHDSS
elif key_type == LIBSSH2_HOSTKEY_TYPE_ECDSA_256:
    server_key_type = LIBSSH2_KNOWNHOST_KEY_ECDSA_256
elif key_type == LIBSSH2_HOSTKEY_TYPE_ECDSA_384:
    server_key_type = LIBSSH2_KNOWNHOST_KEY_ECDSA_384
elif key_type == LIBSSH2_HOSTKEY_TYPE_ECDSA_521:
    server_key_type = LIBSSH2_KNOWNHOST_KEY_ECDSA_521
elif key_type == LIBSSH2_HOSTKEY_TYPE_ED25519:
    server_key_type = LIBSSH2_KNOWNHOST_KEY_ED25519
else:
# ... raise or exit here

type_mask = LIBSSH2_KNOWNHOST_TYPE_PLAIN | LIBSSH2_KNOWNHOST_KEYENC_RAW | server_key_type


kh.checkp(host, port, host_key, type_mask)

# ...

```

**Comment by Red-M** [comment]
I've added this in my own fork.
Could you let me know if it works correctly so that I have more reason to release my fork until the owner of this repository comes back.

**Comment by Addvilz** [comment]
If the above is addressed to me, I am not sure what exactly you would like me to do?... I am not a maintainer of this repo.

**Comment by Red-M** [comment]
@Addvilz It is addressed to you, I know you can't merge that I was simply pointing out that I've fixed that in my own fork and that you can install the fork using pip. :)

**Comment by Addvilz** [comment]
I have the workaround that I already posted above, and that works perfectly fine for my use case.

**Comment by pkittenis** [comment]
0.19.0 has been released.
