### ISSUE TITLE
Error During Installation 

### ISSUE THREAD

**Issue by Sarthak001** [ParallelSSH/ssh2-python#96]
cannot install this library :
Command Used :  **pip install ssh2-python** 
I installed all dependencies like wheel and cmake when i run the command it first builds the library and then its shows the error.

ERROR: 
ERROR: Command errored out with exit status 1:
     command: /home/kahtras/Projects/Flask_serverpanel/flask-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02xlnf7r/ssh2-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02xlnf7r/ssh2-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5qmfop07/install-record.txt --single-version-externally-managed --compile --install-headers /home/kahtras/Projects/Flask_serverpanel/flask-env/include/site/python3.8/ssh2-python
         cwd: /tmp/pip-install-02xlnf7r/ssh2-python/
    Complete output (149 lines):
    CMake Warning (dev) at /home/kahtras/Projects/Flask_serverpanel/flask-env/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/BundleUtilities.cmake:233 (message):
      Policy CMP0080 is not set: BundleUtilities cannot be included at configure
      time.  Run "cmake --help-policy CMP0080" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
    Call Stack (most recent call first):
      /home/kahtras/Projects/Flask_serverpanel/flask-env/lib/python3.8/site-packages/cmake/data/share/cmake-3.18/Modules/BundleUtilities.cmake:242 (_warn_cmp0080)
      tests/CMakeLists.txt:39 (include)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- The following features have been enabled:
    
     * Shared library, creating libssh2 as a shared library (.so/.dll)
     * Compression, using zlib for compression
     * "none" cipher
     * "none" MAC
     * diffie-hellman-group-exchange-sha1, "new" diffie-hellman-group-exchange-sha1 method
    
    -- The following REQUIRED packages have been found:
    
     * ZLIB
     * OpenSSL
    
    -- The following features have been disabled:
    
     * Logging, Logging of execution with debug trace
    
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-02xlnf7r/ssh2-python/src
    [ 23%] Built target libssh2
    [ 23%] Built target copy_example_dependencies
    [ 25%] Built target example-sftp_write_nonblock
    [ 27%] Built target example-scp
    [ 29%] Built target example-sftp_mkdir
    [ 31%] Built target example-scp_write_nonblock
    [ 33%] Built target example-sftp
    [ 35%] Built target example-scp_write
    [ 37%] Built target example-sftp_nonblock
    [ 39%] Built target example-sftp_write
    [ 41%] Built target example-sftpdir_nonblock
    [ 42%] Built target example-direct_tcpip
    [ 44%] Built target example-sftp_mkdir_nonblock
    [ 46%] Built target example-ssh2_agent
    [ 47%] Built target example-sftp_write_sliding
    [ 49%] Built target example-scp_nonblock
    [ 51%] Built target example-sftp_RW_nonblock
    [ 53%] Built target example-sftp_append
    [ 55%] Built target example-ssh2
    [ 57%] Built target example-sftpdir
    [ 59%] Built target example-ssh2_exec
    [ 61%] Built target example-ssh2_echo
    [ 63%] Built target example-subsystem_netconf
    [ 65%] Built target example-tcpip-forward
    [ 65%] Built target copy_test_dependencies
    [ 67%] Built target openssh_fixture
    [ 69%] Built target session_fixture
    [ 71%] Built target runner
    [ 73%] Built target test_public_key_auth_succeeds_with_correct_rsa_key
    [ 75%] Built target test_password_auth_fails_with_wrong_password
    [ 77%] Built target test_public_key_auth_fails_with_wrong_key
    [ 79%] Built target test_password_auth_fails_with_wrong_username
    [ 81%] Built target test_hostkey_hash
    [ 83%] Built target test_password_auth_succeeds_with_correct_credentials
    [ 84%] Built target test_keyboard_interactive_auth_fails_with_wrong_response
    [ 86%] Built target test_public_key_auth_succeeds_with_correct_ed25519_key_from_mem
    [ 88%] Built target test_public_key_auth_succeeds_with_correct_encrypted_rsa_key
    [ 90%] Built target test_keyboard_interactive_auth_succeeds_with_correct_response
    [ 92%] Built target test_public_key_auth_succeeds_with_correct_ed25519_key
    [ 94%] Built target test_public_key_auth_succeeds_with_correct_encrypted_ed25519_key
    [ 96%] Built target test_public_key_auth_succeeds_with_correct_rsa_openssh_key
    [ 98%] Built target test_public_key_auth_succeeds_with_correct_dsa_key
    [100%] Built target test_hostkey
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/__init__.py -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/_version.py -> build/lib.linux-x86_64-3.8/ssh2
    running egg_info
    writing ssh2_python.egg-info/PKG-INFO
    writing dependency_links to ssh2_python.egg-info/dependency_links.txt
    writing top-level names to ssh2_python.egg-info/top_level.txt
    reading manifest file 'ssh2_python.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'docker'
    warning: no previously-included files found matching '.travis.yml'
    writing manifest file 'ssh2_python.egg-info/SOURCES.txt'
    copying ssh2/__init__.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/agent.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/agent.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/agent.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/c_pkey.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/c_sftp.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/c_ssh2.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/c_stat.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/channel.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/channel.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/channel.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/error_codes.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/error_codes.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/error_codes.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/exceptions.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/exceptions.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/fileinfo.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/fileinfo.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/fileinfo.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/knownhost.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/knownhost.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/knownhost.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/listener.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/listener.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/listener.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/pkey.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/pkey.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/pkey.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/publickey.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/publickey.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/publickey.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/session.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/session.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/session.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/sftp.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/sftp.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/sftp.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/sftp_handle.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/sftp_handle.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/sftp_handle.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/statinfo.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/statinfo.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/statinfo.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/utils.c -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/utils.pxd -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/utils.pyx -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/libssh2.so -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/libssh2.so.1 -> build/lib.linux-x86_64-3.8/ssh2
    copying ssh2/libssh2.so.1.0.1 -> build/lib.linux-x86_64-3.8/ssh2
    running build_ext
    building 'ssh2.channel' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/ssh2
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ilibssh2/include -I/home/kahtras/Projects/Flask_serverpanel/flask-env/include -I/usr/include/python3.8 -c ssh2/channel.c -o build/temp.linux-x86_64-3.8/ssh2/channel.o -O3
    ssh2/channel.c:4:10: fatal error: Python.h: No such file or directory
        4 | #include "Python.h"
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/kahtras/Projects/Flask_serverpanel/flask-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-02xlnf7r/ssh2-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-02xlnf7r/ssh2-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5qmfop07/install-record.txt --single-version-externally-managed --compile --install-headers /home/kahtras/Projects/Flask_serverpanel/flask-env/include/site/python3.8/ssh2-python Check the logs for full command output.

**Comment by Sarthak001** [comment]
was trying to install for python 3.8. i hope this library will soon support python 3.8

**Comment by Red-M** [comment]
This is supported in #94
